### PR TITLE
Added npm as dependency

### PR DESCRIPTION
**Pull request by saurabh95**
Fixes https://github.com/adobe/brackets/issues/13312

### CODE REVIEW

**Comment by saurabh95** [comment]
@ficristo Updated the code on production server as well, Could you please verify it?

**Comment by ficristo** [comment]
Unfortunately the registry now give me this error:
"The extension package is invalid: An error occurred, but unfortunately I don't know how to say this nicely: NPM_INSTALL_FAILED"

**Comment by saurabh95** [comment]
@RationalCoding You also were also facing a similar issue, how did you resolve it?

**Comment by RationalCoding** [comment]
@ficristo My issue was having an empty "dependencies" field in my package.json.

ie)
```
"dependencies": {}
```

**Comment by ficristo** [comment]
I removed the "dependencies" fields from the package.json of https://github.com/ficristo/brackets-panels-hack and I was able to upload it.
But I wasn't able to upload https://github.com/ficristo/brackets-terminal-x where I cannot remove the "dependencies" field.
@saurabh95 maybe we should not use npm install on the registry? I don't know...

**Comment by saurabh95** [comment]
@ficristo I tried uploading a test extension using the same dependencies as yours, and I got this error on console.
````
npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/Users/kathpali/Desktop/brackets-registry/node_modules/npm/bin/npm-cli.js" "install" "--production"
npm ERR! node v0.10.25
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! node-pty@0.6.3 install: `node scripts/install.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the node-pty@0.6.3 install script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/w1/xd2sb6bd48712cvhz1nrf7d00000gn/T/bracketsPackage_11744-36843-1ty52xv/light-theme123/npm-debug.log


I think there is an issue with the `node-pty` version, it may not be compatible with the npm version 3.10.10

**Comment by saurabh95** [comment]
@RationalCoding I noticed why your extension was failing as in https://github.com/adobe/brackets-registry/blob/master/deps/brackets-extensibility/npm-installer.js#L117 we are checking only for `packageJson.dependencies`, we also need to check `packageJson.dependencies.length`. I will fix this in brackets and port the code to brackets-registry

**Comment by petetnt** [comment]
Can we update the `node` version? Is it really still at 0.10?

**Comment by saurabh95** [comment]
We have upgraded node version on the server to 6.9.5. Actually I had changed my node version to 0.10.25 and forgot to update it. Updated it now, also edited the error log.

**Comment by ficristo** [comment]
I'm quite sure I used node 6 and npm 3 to develop my extension, I'll check.
Do you have also an .npmrc file? It is possible my extension fails to run `npm install` because of it.
I think node-pty is compatible with node 6 and node 7 but it requires a c++ compiler.
I'm lost why it doesn't work on the registry...

**Comment by zaggino** [comment]
Because `node-pty` depends on native dependencies, which have to be built upon installation, this can be a problem if build tools are not installed on the machine.

Check this: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

```
install build tools

To compile and install native addons from npm you may also need to install build tools:

sudo apt-get install -y build-essential
```

So the question is, are the `build-essential` tools installed on the registry machine?

More reading on that here: https://github.com/nodejs/node-gyp#installation

**Comment by saurabh95** [comment]
I just checked build-essential is installed on the registry machine.

**Comment by ficristo** [comment]
The check for a package.json with an empty dependencies field that was added is fine to avoid a `npm install` which would result in a no op, but `npm install` should have worked.
Why it failed in the registry?

**Comment by saurabh95** [comment]
Yeah ideally it should not fail.
Also I tried solving the issue in my local(macOS) and I was able to solve it by cleaning the npm cache, I did the same in production and restarted the app, but the issue is still there.

**Comment by zaggino** [comment]
What's the content of `npm-debug.log` when the install fails?

**Pull request merged**
