### PR TITLE
Make npm test work on Windows and upgrade dev dependecies

### PR DESCRIPTION
**Pull request by ficristo**
I had some problems to run tests on Windows, this should fix it.
I've upgraded all dev dependencies but jslint because it is not actually used (if you run it is full of errors) and because I'll replace it with ESLint.

### CODE REVIEW

**Comment by zaggino** [comment]
:+1:

**Comment by ficristo** [comment]
so fast :open_mouth:

**Comment by ficristo** [comment]
Thank you!

**Comment by zaggino** [comment]
:sunglasses: np, it's not a PR that needs talking about

**Pull request merged**
