### PR TITLE
Updated Brackets Extensibility - from brackets/src/extensibility/node to brackets-registry/deps/brackets-extensibility

### PR DESCRIPTION
**Pull request by saurabh95**

### CODE REVIEW

**Comment by ficristo** [comment]
We should update the deps at Brackets first.

**Comment by saurabh95** [comment]
You mean merging this first, https://github.com/adobe/brackets/pull/12933 ?

**Comment by zaggino** [comment]
In my opinion, we shouldn't have a tar file here. The more transparent way would be just to create a folder here like `lib-brackets` or something and copy the files from brackets there, with a note that this file is a copy of `https://....` in adobe/brackets. I don't think there's any bonus of having this archive here. Dependencies can be extracted to root package.json

**Comment by saurabh95** [comment]
Yeah using folder instead of tar would be better. I will add the steps in the wiki.
Also once we are done with upgrading node in the brackets-registry prod server, then we can merge https://github.com/adobe/brackets/pull/12933 and then I will pull the latest brackets-extensibility from brackets to registry.

**Comment by petetnt** [comment]
Why don't we just yank the dependency into it's own repo, publish it to `npm` and install it with `npm`?

**Comment by zaggino** [comment]
That's probably the best solution :)

**Comment by ficristo** [comment]
If this PR is a prerequisite to update the extensibility/node deps, I'm fine with it.

**Comment by swmitra** [comment]
I am fine with this approach for now as it can complement the extensiblity dependency management PR by  @zaggino. I am merging this PR, so that I can merge the other PR by @zaggino as well.

**Pull request merged**
